// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jovevoctodkdhwraimwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvdmV2b2N0b2RrZGh3cmFpbXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTIxNzcsImV4cCI6MjA3MDEyODE3N30.TIiL0ibcnuUscwMnBnNdttIedjBvjHig_zGhXm6x-60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});